#!/bin/bash
SP_OPTION=""
USAGE="usage: $0 [a/b] [on/off])"

if [ "$#" -lt "2" ]; then echo $USAGE; exit; fi

case "$1" in
  "b")
    SP_OPTION="-g"
    ;;
  "a")
     SP_OPTION=""
    ;;
  *)
    echo $USAGE
esac

case "$2" in
  start)
    CMD="Play_stapl.py $SP_OPTION i10 500321c0 i16 aff00000 i20 0 i21 0"
    Play_stapl.py $SP_OPTION i10 500321c0 i16 aff00000 i20 0 i21 0 |./splayer_dump.py
    ;;
  on)
    CMD="Play_stapl.py $SP_OPTION i16 aff00000 > /dev/null"
    Play_stapl.py $SP_OPTION i16 aff00000 > /dev/null
    ;;
  off)
    CMD="Play_stapl.py $SP_OPTION i16 0 > /dev/null"
    Play_stapl.py $SP_OPTION i16 0 > /dev/null
    ;;
  1)
    CMD="Play_stapl.py $SP_OPTION i16 cff00000 > /dev/null"
    Play_stapl.py $SP_OPTION i16 cff00000 > /dev/null
    ;;
  *)
    echo $USAGE
    exit
esac

# the nice 'method' does not work
#$CMD
echo "Executed: $CMD"
