#!/bin/bash
# Setup the sequencer for different types of run
# Note, the sequencer Repeat command (code xxx1nnnn repeats the previous command nnnn times 

case "$1" in
  cal) # for internal trigger with CalSR
    CMD="Play_stapl.py i16 00000020 00110002 002000E0 00300020 00410008 00500060 00600020 00710002 008000A0 00900020 00A10800 00B20020"
#                          FM       R2       FM+PARst FM       R8       FM+Cal   FM       R2       FM+L1    FM       R800     FM+EOL
    ;;
  ped) # for internal trigger without CalSR
    CMD="Play_stapl.py i16 00000020 00110002 002000E0 00300020 00410008 00500020 00600020 00710003 008000A0 00900020 00A10800 00B20020"
#                          FM       R2       FM+PARst FM       R8       FM       FM       R3       FM+L1    FM       R800     FM+EOL
    ;;
  trig) # For external trigger
    CMD="Play_stapl.py i16 00000020 00110800 002000E0 00320020"
#                          FM       R800     FM+PARst FM+EOL
    ;;
  svx) # For downloading SVXs
    CMD="Play_stapl.py i16 00000020 0032000"
    ;;
  *)
    echo "usage: $0 ped/cal/trig/svx"
    exit
esac

echo "Executing $CMD"

#$CMD |./splayer_dump.py
$CMD > /dev/null
